version: '3.9'
services:
  aws_psql:
    image: postgres:alpine
    ports:
      - 5432:5432 
    container_name: aws_psql 
    restart: always
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=123 
      - POSTGRES_DB=aws_db 
      - POSTGRES_INITDB_ARGS=--username=postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - iff

  app:
    ports:
      - 3001:3001 
    networks:
      - iff
    container_name: aws_app
    environment:
          - DB_USERNAME=postgres 
          - DB_PASSWORD=123 
          - DB_DATABASE=aws_db 
          
    links:
      - aws_psql
    depends_on:
      - aws_psql
    build:
      context: .
      dockerfile: Dockerfile

  pgadmin4:
    image: dpage/pgadmin4
    container_name: aws_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: italo.magalhaes@gsuite.iff.edu.br
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - '8080:80'
    links:
      - aws_psql
    depends_on:
      - aws_psql
    networks:
      - iff

networks:
  iff:
    driver: bridge

volumes:
  pg-data:
  init:
